logging.level:
  org.hibernate.SQL: DEBUG


spring.cloud.openfeign.client.config:
  shipping-provider:
    url: http://localhost:9999/shipping
  payment-gateway:
    url: http://localhost:9999/payment


order.prop: 2
payment.app.client-name: modulith-app